### ISSUE TITLE
Partial hip bone found after reproducing the pre-processing in Totalsegmentor-hip dataset

### ISSUE THREAD

**Issue by JixiangChen-Jimmy** [naamiinepal/XrayTo3DPreprocess#5]
Dear authors,

Thanks for the awesome work. I notice that in the provided workflow, the incomplete bone shape subject is rejected. (The CT Scans were choosen based on whether full bone shape were available (partial hip scans were rejected manually).) However, when I run the pre-processing code in , I find some data demonstrate partial hip label. It shows that some segmentation label are in the boundary, which indicates incomplete segmentation of the label and the correponding bone CT.

I follow the provided scripts, the cutted physical size is set to 288. Since the original CT scan spacing is (1.5, 1.5, 1.5), the result is of shape (192,192,192). And I found this 'label on the boundary effect' on data 's0012' and 's0013', where the left and right side of seg_roi demonstrate incomplete bones.

Is there any parameters error in the config file?

**Comment by msrepo** [comment]
Thank you for pointing this out. As you correctly inferred, partial hip shapes were rejected, first based on voxel-count-threshold and then manually looking for partial shapes, for example s0006.

The shape that have significant portion of their hip shape cut-off in the CT scan and those that either do not have hip  are listed in the `workflow/totalsegmentator/totalsegmentor_hip/totalsegmentor_hip_unusable.list`
Hip scans with very little cut-off, (example below),  mainly due to the choice of voxel volume (192, 192, 192), for example 's0012' and 's0013' were not kept in the unusable list. Finally, the usable list of scans is listed in `workflow/totalsegmentator/totalsegmentor_hip/hip_subjects.csv`. 

s0006
![snapshot0001](https://github.com/naamiinepal/XrayTo3DPreprocess/assets/10219364/24469967-a6cb-47be-93b1-fccd01faa5a1)
s0012
![snapshot0002](https://github.com/naamiinepal/XrayTo3DPreprocess/assets/10219364/f4d44d04-0127-488b-bb55-e02ad2be05d3)


The main motivation behind these choices was that examples like s0006 did not help define the shape prior of the hip ( they were too different), whereas shapes like s0012 which more or less helped define the shape prior but were cut-off by only few voxels should still be useful.

Hope this answers the question. Thank you.

**Comment by JixiangChen-Jimmy** [comment]
Thanks for your prompt reply! Point this out just to check whether my observation is correct. Will this influence the estimation of some clinical measures?

**Comment by msrepo** [comment]
Yes! Good observation and excellent followup question. 

In short, this will influence estimation of Anterior Superior Illiac Spine (ASIS). We had to cut corners here because the 288^3 volume (divisible by 2^5 for five levels of maxpool) is already big for us to train a swinunetr with batch size 1 in RTX3090. 
As shown in example below, there are atleast a few such hips whose extents go beyond 288^3 and are clipped. We could have increased the volume to 320^3 to accomodate more hip extents.   
![image](https://github.com/naamiinepal/XrayTo3DPreprocess/assets/10219364/b36f4358-b2cd-4351-988a-48890757d55f)

**Comment by JixiangChen-Jimmy** [comment]
Thanks for the suggestion, I got it. I will extend to physical size so that it will contain the entire label segmentations.
